### ISSUE TITLE
Update to handle homebrew PHP management changes

### ISSUE THREAD

**Issue by tauno** [thinkshout/ts_environment#15]
# Upgrade steps

- [x] Make sure you have the latest working copy of ts_environment (this repo) in your home directory:
```sh
cd ~
git clone git@github.com:thinkshout/ts_environment.git

cd ~/ts_environment
git checkout master
git pull
```

## Install rmtrash

- [x] You'll need this later.
```sh
brew install rmtrash
```

## Stop PHP services

- [x] Stop php
```sh
brew services list
brew services stop [any running php]
```

## Remove all existing PHP packages
```sh
brew list | grep php
```

- [x] Review list - all of these will be uninstalled
```sh
brew uninstall --force $(brew list | grep php)
```

- [x] If any of these fail by complaining that some directory is not empty in `/usr/local/Cellar/phpXX`, you'll need to `rmtrash /usr/local/Cellar/phpXX` and then repeat the `brew uninstall` command.

- [x] Check for stragglers:
```sh
brew list | grep php
brew list | grep drupal
brew list | grep terminus
```

- [x] Uninstall any stragglers, e.g.
```sh
brew uninstall --force drupal-code-sniffer
brew uninstall --force drupalconsole
brew uninstall --force terminus
```

- [x] There might be a couple that won't go away... Hit them with the hammer:
```sh
rmtrash /usr/local/Cellar/stragglername

# or the bigger hammer
rm -rf /usr/local/Cellar/stragglername
```

## Remove old php config

- [x] Remove directories
```sh
rmtrash /usr/local/lib/php
rmtrash /usr/local/etc/php
rmtrash /usr/local/etc/PHP_CodeSniffer
rmtrash /usr/local/etc/php-code-sniffer
```

## Clean up

- [x] Clean up homebrew
```sh
brew update
brew cleanup
brew prune
brew outdated
```

- [x] Clean up composer global
```sh
composer global info -N
composer global remove straggler
```

## Install

- [x] Install packages
```sh
brew bundle --file=Brewfile-dev
```

- [x] Run the ts install script for php
```sh
./scripts/php.sh
```

- [x] Verify php binary
```
which php
php -v
```

- [x] Install php switcher
```
cp config/ts.zsh ~/.oh-my-zsh/custom
```

- [x] In PHPstorm, go to Preferences -> Languages & Frameworks -> PHP -> Code Sniffer
Click the "..." on the right next to the configuration, and enter this path: `/Users/USERNAME/.composer/vendor/bin/phpcs`

## Bonus round

- [x] `cp config/drushrc.php ~/.drush`
- [ ] [Generate a trusted SSL certificate for localhost](https://github.com/thinkshout/ts_environment/wiki/Generate-a-trusted-SSL-certificate-for-localhost)

# To do

https://github.com/Homebrew/homebrew-php/issues/4721

- [x] Figure out how to install items no longer available via Brew (`brew tap homebrew/php` is gone):
  - [x] drush (composer global?)
  - [x] drupal-code-sniffer
  - [x] drupalconsole (composer version conflicts with composer-debug 4.0.8)
  - [x] ~php-mcrypt (available via pecl)~
  - [x] ~php-redis (available via pecl)~
  - [x] php-xdebug (available via pecl)
  - [x] php-opcache (now included automatically with php)

- [x] Update Brewfile
- [x] Add new installations
- [x] Update configuration 
- [x] Update instructions

**Comment by unclegcb** [comment]
I've started this work on the php72 branch. If anyone can have a look that'd be awesome. Would love to not have to use pecl/pear and composer at all but I can't figure out where else to get those packages now.

**Comment by unclegcb** [comment]
@wxactly @tauno feedback welcome. Also... testing seems like an adventure. Either of you have a clean system handy?

**Comment by wxactly** [comment]
Wow. I saw homebrew was dropping support for homebrew/php... did not realize that meant it was dropping support for like every php package! We have our work cut out for us. 😫 

I don't think we have any need for pear - but agreed about pecl... unfortunately it looks like that's where we need to grab php extensions now.

For drush, terminus, etc, we should have the script install [cgr](https://github.com/consolidation/cgr) and then use cgr to install global php binaries.

I'm going to go ahead and open up a PR on `php72` now so I can leave some feedback in the branch

**Comment by wxactly** [comment]
Some relevant stuff in these posts (ignore all of the apache stuff):

https://getgrav.org/blog/macos-sierra-apache-upgrade-homebrew
https://getgrav.org/blog/macos-sierra-apache-multiple-php-versions
https://getgrav.org/blog/macos-sierra-apache-mysql-vhost-apc

**Comment by tauno** [comment]
@wxactly those links are the ones I was looking at to fix my local environment - just haven't gotten the time to do it yet.

@unclegcb I saw a reference that mcrypt was packaged with the core php distribution now - maybe you've already verified that it isn't.
