### ISSUE TITLE
Some standard git configuration

### ISSUE THREAD

**Issue by mariacha** [thinkshout/ts_environment#22]
After the git tech meeting, I asked about the command that automatically did a rebase when you pull, and whether it's standard on our TS machines. It's not, and maybe there are some other things we should configure by default. See https://thinkshout.slack.com/archives/C03GTM56A/p1539194820000100

- [x] Add `git config --global pull.rebase true` based on https://git-scm.com/docs/git-config#git-config-pullrebase
- [ ] ...?...

**Comment by wxactly** [comment]
Added the one from above, but happy to add more in the event that we surface any others! c6eed6b
