### ISSUE TITLE
Rbenv is added to .bashrc but not .zshrc

### ISSUE THREAD

**Issue by mariacha** [thinkshout/ts_environment#24]
I see the logic for this here:

https://github.com/thinkshout/ts_environment/blob/master/environment_setup.sh#L96

but I only got the command in my .bashrc file.

I suspect that's because I was running the command to install the script IN bash, because Zshell was only just installed by this same script. Does that seem true?

Any danger in just adding it both places?

Because I didn't know  this I'm leaving it here: The result, if you don't add this line to the correct command line tool, is that attempting to install a gem without sudo results in:

```
You don't have write permissions for the /Library/Ruby/Gems/2.0.0 directory
```

**Comment by wxactly** [comment]
Fixed in 3ac84ae!
