### ISSUE TITLE
DNSmasq ignored during Guzzle behat calls

### ISSUE THREAD

**Issue by mariacha** [thinkshout/ts_environment#26]
Seems to be related to the recent php homebrew changes. See: https://thinkshout.slack.com/archives/C03GTM56A/p1549575681339700

Sounds like we're having to add the clean url to our `/etc/hosts` file, but that shouldn't be necessary if we're using DNSmasq, right?

What IS working:
- Visiting the site in a browser, like this: http://web.wfw8.localhost/
- Curling the site like this: `curl http://web.wfw8.localhost/`

What is NOT working:

A guzzle call like this:

```
$client = new GuzzleHttp\Client([
  // Base URI is used with relative requests
  'base_uri' => 'http://web.wfw8.localhost',
  // You can set any number of default request options.
  'timeout'  => 2.0,
]);

try {
  $response = $client->request('GET', '/');
}
catch (Exception $exception) {
  print "";
}
```

The error is: `cURL error 6: Could not resolve: web.wfw8.localhost (Domain name not found) (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)`

**Comment by mariacha** [comment]
UPDATE: This does NOT work:

```
  $curl = curl_init();
  curl_setopt($curl, CURLOPT_URL, 'http://web.wfw8.localhost');

  $result = curl_exec($curl);
  $error = curl_error($curl);
```

$error is "Could not resolve: web.wfw8.localhost (Domain name not found)" -- so same thing.

**Comment by wxactly** [comment]
This is not helpful since there is no answer, but I see some other folks on the internet experiencing this problem as well - https://stackoverflow.com/q/54571414/1456495 - maybe newer php versions? Maybe the new php homebrew formulas?

**Comment by wxactly** [comment]
Circling back around to this issue because I believe this is the fix - I just haven't had the opportunity to test it out yet: https://stackoverflow.com/a/54908305/1456495
```
brew uninstall curl-openssl --ignore-dependencies
```

**Comment by mariacha** [comment]
Fixes it for me!

**Comment by mariacha** [comment]
I haven't had this problem for a long time (maybe because I got a new computer?) So closing.
