### ISSUE TITLE
Consider valet for nginx, dnsmasq, php management

### ISSUE THREAD

**Issue by tauno** [thinkshout/ts_environment#27]
Laravel's valet project/tool worked well for me to get my own environment working again. We should consider replacing our own homebrew management of nginx, php and dnsmasq with theirs - https://laravel.com/docs/5.8/valet

**Comment by mariacha** [comment]
What questions do we have about this? @wxactly you're probably in the best place to chew on it, but we can talk them over with the bigger group. Here's what I came up with:

1. What are the benefits? (Shareability with clients, shareability with debugging)
2. What are the risks? (Time, ongoing support, training, reliance on third-party)

**Comment by mariacha** [comment]
The endpoint of this discussion is -- next time there's a big hassle problem involved in the ts_environment it's worth considering switching us over.
