### ISSUE TITLE
Migrate Homebrew dependencies to Brew Bundle

### ISSUE THREAD

**Issue by wxactly** [thinkshout/ts_environment#3]
https://github.com/Homebrew/homebrew-bundle
## Usage

Create a `Brewfile` in the root of your project:

```
$ touch Brewfile
```

Then list your Homebrew based dependencies in your `Brewfile`:

``` ruby
cask_args appdir: '/Applications'
tap 'caskroom/cask'
tap 'telemachus/brew', 'https://telemachus@bitbucket.org/telemachus/brew.git'
brew 'imagemagick'
brew 'mysql', restart_service: true, conflicts_with: ['homebrew/versions/mysql56']
brew 'emacs', args: ['with-cocoa', 'with-gnutls']
cask 'google-chrome'
cask 'java' unless system '/usr/libexec/java_home --failfast'
cask 'firefox', args: { appdir: '~/my-apps/Applications' }
```

You can then easily install all of the dependencies with one of the following commands:

```
$ brew bundle
```

If a dependency is already installed and there is an update available it will be upgraded.

**Comment by tauno** [comment]
This is done!
